spring:
  application:
    name: ielts-platform-backend
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ielts_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
